Add new function load_env_var
economiagovbr/FastETL pull request #60
Opened 2022-05-06 19:17 UTC by edulauer

Add a new custom_function named load_env_var, useful for GreatExpectationOperator in airflow DAGs

2022-05-16 14:50 UTC, augusto-herrmann requested changes
@edulauer dei uma olhada no PR. Veja o que acha das sugestões, por favor.

2022-05-16 14:50 UTC, augusto-herrmann commented on custom_functions/fast_etl.py
> +
Sugiro deixar sem os "`#`" no início da linha de texto.

```suggestion
    Atribui a string de conexão para uma variável de ambiente em execução.
    Útil para executar o Great Expectations através de uma DAG, utilizando
    as credenciais das connections do próprio airflow e referenciando
    nas variáveis setadas no arquivo `great_expectations.yml`.

```

2022-05-16 14:50 UTC, augusto-herrmann commented on custom_functions/fast_etl.py
> +    os.environ[conn_name] = connection_string
Sugiro deixar sempre um newline no final do arquivo, conforme recomendação da PEP8.
```suggestion
    os.environ[conn_name] = connection_string
    
```

2022-05-16 14:50 UTC, augusto-herrmann commented on custom_functions/fast_etl.py
> +    os.environ[conn_name] = connection_string
Exportar as credenciais para uma variável de ambiente não poderia aumentar a superfície de ataque?

A princípio não sou contra, só queria saber se houve alguma reflexão quanto a isso.

2022-05-17 14:31 UTC, edulauer commented
@augusto-herrmann, pelo que entendi a biblioteca/função os.environ[...]  apenas define a variavel de ambiente durante a execução do processo em python, ela não fica armazenada como variável de ambiente no Sistema Operacional.

2022-05-17 14:38 UTC, merged