Check data_column field type
economiagovbr/FastETL pull request #89
Opened 2022-08-19 20:23 UTC by edulauer

On incremental table synchronization, checks if date_column type is date or datetime before building the select SQL statement to compare the tables from distinctive sources.

2022-08-19 20:29 UTC, augusto-herrmann commented
Boa! Vou comentar em português, já que o resto do FastETL está em português.

Já que está mexendo nesse método, faço algumas sugestões:
* transformar em dosctring o comentário que precede o método
* incluir type hinting do retorno do método

2022-08-19 21:18 UTC, edulauer commented
@augusto-herrmann beleza!

2022-08-20 12:05 UTC, augusto-herrmann requested changes
Tá excelente! Só mais algumas alteraçõezinhas.

Precisa ainda importar no início do arquivo, se já não tiver:

```python
from typing import Tuple
```

2022-08-20 12:05 UTC, augusto-herrmann commented on custom_functions/fast_etl.py
> +                table: str, date_column: str, key_column: str) -> str:
```suggestion
                table: str, date_column: str, key_column: str) -> Tuple[str, str]:
```

Na verdade, [o retorno é uma tupla](https://github.com/economiagovbr/FastETL/blob/b781f583166f25286745ab8910ae120f70e3efda/custom_functions/fast_etl.py#L544).

2022-08-20 12:05 UTC, augusto-herrmann commented on custom_functions/fast_etl.py
> +        atualizações na origem.
```suggestion
        atualizações na origem.
        
        Returns:
                Tuple[str, str]: Tupla contendo o valor máximo e a condição
                        where da query sql.
```

Retorno na docstring.

2022-08-22 13:31 UTC, edulauer commented
@augusto-herrmann, ok, alterações realizadas!

2022-08-22 13:34 UTC, augusto-herrmann approved these changes
Perfeito!

Valeu demais.

2022-08-22 13:34 UTC, merged